import { Task, TaskColumnData } from "../types";

export const initialTasks: Task[] = [
    {
        id: 't-1',
        title: 'Design System Update',
        description: 'Update the color palette and typography in the global CSS to match the new brand guidelines.',
        status: 'todo',
        priority: 'high',
        area: 'UX Design',
        collaboratorIds: ['u-1'],
        attachments: [],
        commentsCount: 2,
        createdAt: '2023-10-25T10:00:00Z',
    },
    {
        id: 't-2',
        title: 'Kanban Board Logic',
        description: 'Implement drag and drop functionality using @hello-pangea/dnd library.',
        status: 'in-progress',
        priority: 'high',
        area: 'Desenvolvimento',
        coverImage: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        collaboratorIds: ['u-2', 'u-3'],
        attachments: [],
        commentsCount: 5,
        createdAt: '2023-10-26T14:30:00Z',
    },
    {
        id: 't-3',
        title: 'Client Meeting Preparation',
        description: 'Prepare slides and gathering metrics for the monthly review with Acme Corp.',
        status: 'review',
        priority: 'medium',
        area: 'Atendimento',
        collaboratorIds: ['u-1'],
        attachments: [
            { id: 'a-1', name: 'Slides.pdf', type: 'pdf', url: '#' }
        ],
        commentsCount: 0,
        createdAt: '2023-10-27T09:15:00Z',
    },
    {
        id: 't-4',
        title: 'Fix Navigation Bug',
        description: 'Mobile menu not closing when clicking outside the drawer.',
        status: 'done',
        priority: 'low',
        area: 'Desenvolvimento',
        collaboratorIds: ['u-2'],
        attachments: [],
        commentsCount: 1,
        createdAt: '2023-10-24T16:45:00Z',
    },
    {
        id: 't-5',
        title: 'Social Media Strategy',
        description: 'Plan the content calendar for the next month across all platforms.',
        status: 'todo',
        priority: 'medium',
        area: 'Social Media',
        collaboratorIds: ['u-3'],
        attachments: [],
        commentsCount: 3,
        createdAt: '2023-10-28T11:00:00Z',
    },
    {
        id: 't-6',
        title: 'Data Analysis Report',
        description: 'Analyze user engagement metrics from the last quarter and compile a report.',
        status: 'review',
        priority: 'high',
        area: 'Dados',
        collaboratorIds: ['u-1', 'u-2'],
        attachments: [{ id: 'a-2', name: 'Metrics_Q3.csv', type: 'other', url: '#' }],
        commentsCount: 8,
        createdAt: '2023-10-29T10:00:00Z',
    },
    {
        id: 't-7',
        title: 'New Feature Branding',
        description: 'Create visual identity for the upcoming "Auto-Magic" feature.',
        status: 'in-progress',
        priority: 'medium',
        area: 'UX Design',
        collaboratorIds: ['u-1'],
        attachments: [],
        commentsCount: 4,
        createdAt: '2023-10-30T14:00:00Z',
    },
    {
        id: 't-8',
        title: 'Marketing Email Blast',
        description: 'Set up the sequence for the Black Friday promotion.',
        status: 'todo',
        priority: 'low',
        area: 'Marketing',
        collaboratorIds: ['u-3'],
        attachments: [],
        commentsCount: 0,
        createdAt: '2023-10-31T09:00:00Z',
    }
];

export const initialColumns: TaskColumnData[] = [
    { id: 'todo', title: 'A fazer', tasks: [] },
    { id: 'in-progress', title: 'Em progresso', tasks: [] },
    { id: 'review', title: 'Em revisão', tasks: [] },
    { id: 'done', title: 'Completo', tasks: [] },
];
